### PR TITLE
Fix copyFile method

### LINKED ISSUE #147: Utils.js: function copyFile always prints "chmod <perms> on <file> failed after copying, ignoring".
solution is to check if there actually was an error, ex. 

```Javascript
if (err) {
    _event.emit('log', 'chmod ' + stats.mode + ' on ' + dest + ' failed after copying, ignoring');
}
```

### PR DESCRIPTION
**Pull request by bambooCZ**
When file doesn't exist after copy, DO NOT COPY IT AGAIN. We will only check its existence again.

fixes #147

### CODE REVIEW

**Comment by adam-lynch** [comment]
We've been having some serious problems around this. See #142. 

When you say "Fix copyFile method", what exactly does this fix? Because I think there might be two / three problems overall.

**Comment by bambooCZ** [comment]
Acording #142, I had the same problem with .icns file. This is fixed in this fix.

IMO, the problem is that when a file is not in destination after copy, another copying is executed.
Solution is not to execute copying again, but only check its existence later.

It works for me. I am using my modification and I haven't encountered this problem again.

**Comment by bambooCZ** [comment]
But yes this is just a workaround. This should be fixed in graceful-fs-extra.copy. It should not call the callback before the file is truly there.

**Comment by swissmanu** [comment]
this fix work for me on osx 10.10 as also on my travis ci build... would really appriciate a merge to the official version of `node-webkit-builder`

**Comment by dubcanada** [comment]
This fixed my issue on Windows.

**Comment by steida** [comment]
Any progress?

**Comment by bambooCZ** [comment]
Are there any problems with it? Adam, have you tested it? Do you need any explanation? Or what is taking you so long?

**Comment by adam-lynch** [comment]
Completely forgot to test it. I'm crazy busy. I'll try test this tonight I swear :smile:.

**Comment by steida** [comment]
Awesome.

**Comment by adam-lynch** [comment]
I still get the EMFILE myself but this does look like an improvement so I'm merging it in.

**Comment by steida** [comment]
emfile? ulimit -n 10000 does not work?

**Comment by adam-lynch** [comment]
@steida there's no `ulimit` command on Windows.

**Comment by jminnick** [comment]
It still seems like there is some type of threshold limit on windows. I can reproduce this "Error: EMFILE, open" issue reliably.

**Pull request merged**
